title: tux2603
description: A page with stuff
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tux2603.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tux2603

markdown: kramdown

# Build settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed